### ISSUE TITLE
move missingMandatoryParameters closer to where it's used

### ISSUE THREAD

**Issue by ghostsquad** [KirkMunro/SnippetPx#2]
https://github.com/KirkMunro/SnippetPx/blob/assembly/SnippetPx/InvokeSnippetCommand.cs#L52

This should probably right above `foreach (PSObject psObject in results)`
https://github.com/KirkMunro/SnippetPx/blob/assembly/SnippetPx/InvokeSnippetCommand.cs#L66

There's no need to create this list if the `else` is not executed.

**Comment by KirkMunro** [comment]
Yeah, you might find a similar issue here or there where I didn't move variable definitions around after adding error handling that I skipped over when implementing the core logic.  I've changed it locally on my system, it will be added to GitHub later.
